# Generated by Django 5.0.6 on 2024-06-16 14:08

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_collection"),
        ("steps", "0011_userstepenroll"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionStepConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("number", models.IntegerField(default=1000, verbose_name="№ шага в коллекции")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовать")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_step_connections",
                        to="collections.collection",
                        verbose_name="Коллекция заданий",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_step_connections",
                        to="steps.step",
                        verbose_name="Шаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция заданий -> Шаг",
                "verbose_name_plural": "2. Коллекции заданий -> Шаги",
                "db_table": "collection_step_connections",
                "ordering": ["pk"],
                "unique_together": {("collection", "step")},
            },
        ),
    ]
