# Generated by Django 5.0.6 on 2024-06-16 13:55

from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Название шага"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовать шаг"),
                ),
            ],
            options={
                "verbose_name": "Шаг",
                "verbose_name_plural": "1. Шаги",
                "db_table": "steps",
                "ordering": ["pk"],
            },
        ),
    ]
