# Generated by Django 5.0.6 on 2024-06-16 13:56

from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0001_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="steps.step",
                    ),
                ),
                ("text", models.JSONField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Шаг [Текстовый]",
                "verbose_name_plural": "2. Шаги [Текстовые]",
                "db_table": "steps_textsteps",
                "ordering": ["pk"],
            },
            bases=("steps.step",),
        ),
    ]
