# Generated by Django 5.0.6 on 2024-06-16 13:56

from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0002_textstep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="steps.step",
                    ),
                ),
                ("video_url", models.URLField(max_length=500, verbose_name="Ссылка на видео")),
            ],
            options={
                "verbose_name": "Шаг [Видео]",
                "verbose_name_plural": "3. Шаги [Видео]",
                "db_table": "steps_videosteps",
                "ordering": ["pk"],
            },
            bases=("steps.step",),
        ),
    ]
