# Generated by Django 5.0.6 on 2024-06-16 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0003_videostep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="steps.step",
                    ),
                ),
                ("text", models.JSONField(verbose_name="Текст вопроса")),
                ("answer", models.CharField(verbose_name="Ответ на вопрос")),
            ],
            options={
                "verbose_name": "Шаг [Вопрос]",
                "verbose_name_plural": "4. Шаги [Вопрос]",
                "db_table": "steps_questionsteps",
                "ordering": ["pk"],
            },
            bases=("steps.step",),
        ),
    ]
