# Generated by Django 5.0.6 on 2024-06-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0005_useranswerforquestionstep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="steps.step",
                    ),
                ),
                ("text", models.JSONField(verbose_name="Легенда задачи")),
                ("input", models.JSONField(verbose_name="Входные данные")),
                ("output", models.JSONField(verbose_name="Выходные данные")),
                ("notes", models.JSONField(verbose_name="Примечания")),
                (
                    "start_code",
                    models.TextField(
                        blank=True, default="", max_length=10000, verbose_name="Дополнительный код"
                    ),
                ),
                (
                    "first_sample",
                    models.IntegerField(default=1, verbose_name="Номер первого сэмпла"),
                ),
                (
                    "last_sample",
                    models.IntegerField(default=3, verbose_name="Номер последнего сэмпла"),
                ),
                ("first_test", models.IntegerField(default=1, verbose_name="Номер первого теста")),
                ("cpu_time", models.IntegerField(default=1, verbose_name="Ограничение по времени")),
                ("memory", models.IntegerField(default=64, verbose_name="Ограничение по памяти")),
            ],
            options={
                "verbose_name": "Шаг [Программирование]",
                "verbose_name_plural": "5. Шаги [Программирование]",
                "db_table": "steps_problemsteps",
                "ordering": ["pk"],
            },
            bases=("steps.step",),
        ),
    ]
