# Generated by Django 5.0.6 on 2024-06-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0008_testforproblemstep"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnswerForProblemStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("code", models.TextField(max_length=10000, verbose_name="Код пользователя")),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python"), ("cpp", "C++")],
                        default="python",
                        max_length=10,
                        verbose_name="Язык программирования",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("PR", "На проверке"),
                            ("OK", "OK"),
                            ("CE", "Ошибка компиляции"),
                            ("WA", "Неправильный ответ"),
                            ("TL", "Превышение времени"),
                            ("ML", "Превышение памяти"),
                            ("UN", "Незвестная ошибка"),
                        ],
                        default="PR",
                        max_length=2,
                        verbose_name="Вердикт",
                    ),
                ),
                ("cpu_time", models.FloatField(null=True, verbose_name="Затраченное время")),
                (
                    "first_fail_test",
                    models.IntegerField(null=True, verbose_name="Первый ошибочный тест"),
                ),
                ("points", models.IntegerField(null=True, verbose_name="Баллы")),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answer_for_problem_steps",
                        to="steps.problemstep",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answer_for_problem_steps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка пользователя",
                "verbose_name_plural": "5. Шаги [Программирование] -> [Ответ]",
                "ordering": ["pk"],
            },
        ),
    ]
