# Generated by Django 5.0.6 on 2024-06-27 22:15

from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0013_userstepbookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStepView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "source",
                    models.CharField(
                        choices=[("LMS", "LMS"), ("BOT", "Телеграм Бот")],
                        default="LMS",
                        max_length=3,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_step_views",
                        to="steps.step",
                        verbose_name="Шаг",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_step_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг -> Просмотр [Сайт]",
                "verbose_name_plural": "9. Шаги -> Просмотры [Сайт]",
                "db_table": "user_step_views",
                "ordering": ["pk"],
            },
        ),
    ]
