# Generated by Django 5.0.6 on 2024-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0014_userstepview"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="bookmarked_by",
            field=models.BigIntegerField(default=0, verbose_name="Счетчик закладок"),
        ),
        migrations.AddField(
            model_name="step",
            name="liked_by",
            field=models.BigIntegerField(default=0, verbose_name="Счетчик лайков"),
        ),
        migrations.AddField(
            model_name="step",
            name="viewed_by",
            field=models.BigIntegerField(default=0, verbose_name="Счетчик просмотров"),
        ),
    ]
