# Generated by Django 5.0.6 on 2024-06-29 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0015_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleChoiceQuestionStep",
            fields=[
                (
                    "step_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="steps.step",
                    ),
                ),
                ("text", models.JSONField(verbose_name="Текст вопроса")),
            ],
            options={
                "verbose_name": "Шаг [Вопрос][Выбор ответа]",
                "verbose_name_plural": "4. Шаги [Вопрос][Выбор ответа]",
                "db_table": "steps_singlechoicesteps",
                "ordering": ["pk"],
            },
            bases=("steps.step",),
        ),
    ]
