# Generated by Django 5.0.6 on 2024-06-29 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0016_singlechoicequestionstep"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerForSingleChoiceQuestionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("answer", models.CharField(verbose_name="Ответ")),
                ("is_correct", models.BooleanField(default=False, verbose_name="Верный ответ")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_for_single_choice_question_steps",
                        to="steps.singlechoicequestionstep",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаг [Вопрос][Выбор ответа] -> [Варианты ответа]",
                "verbose_name_plural": "4. Шаги [Вопрос][Выбор ответа] -> [Варианты ответов]",
                "db_table": "answer_for_single_choice_question_steps",
                "ordering": ["pk"],
            },
        ),
    ]
