# Generated by Django 5.0.6 on 2024-06-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_course"),
        ("steps", "0011_userstepenroll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("title", models.CharField(max_length=50, verbose_name="Название темы")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовать тему"),
                ),
                ("number", models.IntegerField(default=1000, verbose_name="№ темы в курсе")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="courses.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема",
                "verbose_name_plural": "2. Темы",
                "db_table": "topics",
                "ordering": ["pk"],
                "unique_together": {("course", "number")},
            },
        ),
    ]
