# Generated by Django 5.0.6 on 2024-06-16 14:04

from django.conf import settings
from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_topic"),
        ("steps", "0011_userstepenroll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("title", models.CharField(max_length=50, verbose_name="Название урока")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовать урок"),
                ),
                ("number", models.IntegerField(default=1000, verbose_name="№ урока в теме")),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.topic",
                        verbose_name="Тема",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "3. Уроки",
                "db_table": "lessons",
                "ordering": ["pk"],
                "unique_together": {("topic", "number")},
            },
        ),
    ]
