# Generated by Django 5.0.6 on 2024-06-16 14:06

from django.db import migrations, models

import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_authorcourseenroll"),
        ("steps", "0011_userstepenroll"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonStepConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовать шаг в уроке"),
                ),
                ("number", models.IntegerField(default=1000, verbose_name="№ шага в уроке")),
                ("attempts", models.IntegerField(default=-1, verbose_name="Количество попыток")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_step_connections",
                        to="courses.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_step_connections",
                        to="steps.step",
                        verbose_name="Шаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уроки -> Шаг",
                "verbose_name_plural": "4. Уроки -> Шаги",
                "db_table": "lesson_step_connections",
                "ordering": ["pk"],
                "unique_together": {("lesson", "step", "number")},
            },
        ),
    ]
